# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

## !USE TEXT THEME
# theme: jekyll-text-theme # Gem-based Jekyll Themes
remote_theme: kitian616/jekyll-TeXt-theme # Jekyll Remote Theme, see https://github.com/benbalter/jekyll-remote-theme for more information.
# https://tianqi.name/jekyll-TeXt-theme/docs/en/quick-start
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'
## => Site Settings
##############################
text_skin: dark # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: tomorrow-night # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url: https://genomagames.com # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl: /genoma-invaders # does not include hostname
title: Genoma Games
description: >- # this means to ignore newlines until "Language & timezone"
  2D Game Shoot 'em Up like Space Invaders made to teach Game Development with Unity.

## => Language and Timezone
##############################
lang: en # the language of your site, default as "en"
timezone: Europe/Madrid # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values

## => Author and Social
##############################
author:
  type: organization # "person" (default), "organization"
  name: Genoma Games
  url: https://genomagames.com
  # avatar: # path or url of avatar image (square)
  bio: Indie Game Development Studio based in Madrid, Spain.
  email: info@genomagames.com
  facebook: GenomaGames # "user_name" the last part of your profile url, e.g. https://www.facebook.com/user_name
  twitter: GenomaGames # "user_name" the last part of your profile url, e.g. https://twitter.com/user_name
  # weibo: # "user_id"   the last part of your profile url, e.g. https://www.weibo.com/user_id/profile?...
  # googleplus: # "user_id"   the last part of your profile url, e.g. https://plus.google.com/u/0/user_id
  telegram: GenomaGames # "user_name" the last part of your profile url, e.g. https://t.me/user_name
  medium: genoma-games # "user_name" the last part of your profile url, e.g. https://medium.com/user_name
  # zhihu: # "user_name" the last part of your profile url, e.g. https://www.zhihu.com/people/user_name
  # douban: # "user_name" the last part of your profile url, e.g. https://www.douban.com/people/user_name
  # linkedin: # "user_name" the last part of your profile url, e.g. https://www.linkedin.com/in/user_name
  github: GenomaGames # "user_name" the last part of your profile url, e.g. https://github.com/user_name
  # npm: genoma-games # "user_name" the last part of your profile url, e.g. https://www.npmjs.com/~user_name

## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: GenomaGames/genoma-invaders
repository_tree: gh-pages

## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-SA-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: h1,h2,h3 # "h1,h2,h3" (default)

## => Markdown Enhancements
##############################
## Mathjax https://tianqi.name/jekyll-TeXt-theme/docs/en/markdown-enhancements#mathjax
mathjax: false # false (default), true
mathjax_autoNumber: false # false (default), true

## Mermaid https://tianqi.name/jekyll-TeXt-theme/docs/en/markdown-enhancements#mermaid
mermaid: false # false (default), true

## Chart https://tianqi.name/jekyll-TeXt-theme/docs/en/markdown-enhancements#chart
chart: false # false (default), true

## => Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need

## => Sources
##############################
sources: unpkg # bootcdn (default), unpkg

## => Sharing
##############################
sharing:
  provider: false # false (default), "addtoany", "addthis", "custom"

  ## AddThis
  # addthis:
  #   id: # AddThis pubid, e.g. ra-5xxxxxxxxxxx

## => Comments
##############################
comments:
  provider: false # false (default), "disqus", "gitalk", "valine", "custom"

  ## Disqus
  disqus:
    shortname: genoma-games # the Disqus shortname for the site

  ## Gitalk
  # please refer to https://github.com/gitalk/gitalk for more info.
  # gitalk:
  #   clientID: # GitHub Application Client ID
  #   clientSecret: # GitHub Application Client Secret
  #   repository: # GitHub repo
  #   owner: # GitHub repo owner
  #   admin:# GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.
  #     # - your GitHub Id
  ## Valine
  # please refer to https://valine.js.org/en/ for more info.
  # valine:
  #   app_id: # LeanCloud App id
  #   app_key: # LeanCloud App key
  #   placeholder: # Prompt information
  #   visitor: # false (default)
  #   meta: # "[nick, mail, link]" (default) nickname, E-mail, Personal-site

## => Pageview
##############################
pageview:
  provider: false # false (default), "leancloud", "custom"

  ## Leancloud
  # leancloud:
  #   app_id: # LeanCloud App id
  #   app_key: # LeanCloud App key
  #   app_class: # LeanCloud App class

## => Search
##############################
search:
  provider: false # "default" (default), false, "google", "custom"

  ## Google Custom Search Engine
  # google:
  #   custom_search_engine_id: # Google Custom Search Engine ID

## => Analytics
##############################
analytics:
  provider: false # false (default), "google", "custom"

  ## Google Analytics
  # google:
  #   tracking_id: # Google Analytics id for the site
  #   anonymize_ip: false # Anonymize IP tracking for Analytics

## => Build
##############################
# https://jekyllrb.com/docs/configuration/markdown/
markdown: GFM # kramdown, GFM
# https://jekyllrb.com/docs/liquid/tags/#code-snippet-highlighting
highlighter: rouge
# https://jekyllrb.com/docs/permalinks/#global
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - package-lock.json
  - package.json
  - /node_modules
  - /vendor

collections:
  tutorials:
    sort_by: lesson
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      author: AlbertoFdzM
      sharing: false
      license: CC-BY-SA-4.0
      aside:
        toc: false
      show_edit_on_github: false
      show_subscribe: false
      pageview: false
      comment: false
  - scope:
      path: ""
      type: tutorials
    values:
      layout: article
      author: AlbertoFdzM
      sharing: false
      license: CC-BY-SA-4.0
      aside:
        toc: false
      show_edit_on_github: false
      show_subscribe: false
      pageview: false
      comment: false

## => Plugins
##############################

optional_front_matter:
  remove_originals: true

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

relative_links:
  enabled: true
  collections: true

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-relative-links
