# https://pages.github.com/versions/
# https://github.com/jekyll/jekyll/blob/v3.8.7/docs/_docs/configuration.md
# Where things are
# source: .
# destination: ./_site
# collections_dir: .
# plugins_dir: _plugins
# layouts_dir: _layouts
# data_dir: _data
# includes_dir: _includess
# https://jekyllrb.com/docs/assets/#sassscss
# sass:
#   sass_dir: _sass
#   style: compressed
sass:
  style: compressed
collections:
  # posts:
  #   output: true
  tutorials:
    sort_by: lesson
    output: true
    permalink: /:title/

# Handling Reading
# safe: false
safe: true
include:
  - .htaccess
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - package-lock.json
  - package.json
  - node_modules
  - vendor/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
# keep_files:
#   - .git
#   - .svn
# encoding: utf-8
# markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown_ext: md
strict_front_matter: false

# Filtering Content
# show_drafts: null
# limit_posts: 0
# future: false
# unpublished: false

# Plugins
# whitelist: []
# https://github.com/github/pages-gem/blob/master/lib/github-pages/plugins.rb#L21
whitelist:
  # https://github.com/jekyll/jekyll-coffeescript
  - jekyll-coffeescript
  # https://github.com/github/jekyll-commonmark-ghpages
  - jekyll-commonmark-ghpages
  # https://github.com/jekyll/jekyll-feed
  - jekyll-feed
  # https://github.com/jekyll/jekyll-gist
  - jekyll-gist
  # https://github.com/jekyll/github-metadata
  - jekyll-github-metadata
  # https://github.com/jekyll/jekyll-paginate
  - jekyll-paginate
  # https://github.com/jekyll/jekyll-redirect-from
  - jekyll-redirect-from
  # https://github.com/jekyll/jekyll-seo-tag
  # https://jekyll.github.io/jekyll-seo-tag/usage/
  - jekyll-seo-tag
  # https://github.com/jekyll/jekyll-sitemap
  - jekyll-sitemap
  # https://github.com/benbalter/jekyll-avatar
  - jekyll-avatar
  # https://github.com/jekyll/jemoji
  - jemoji
  # https://github.com/jekyll/jekyll-mentions
  - jekyll-mentions
  # https://github.com/benbalter/jekyll-relative-links
  - jekyll-relative-links
  # https://github.com/benbalter/jekyll-optional-front-matter
  - jekyll-optional-front-matter
  # https://github.com/benbalter/jekyll-readme-index
  - jekyll-readme-index
  # https://github.com/benbalter/jekyll-default-layout
  - jekyll-default-layout
  # https://github.com/benbalter/jekyll-titles-from-headings
  - jekyll-titles-from-headings
  # https://github.com/benbalter/jekyll-include-cache
  - jekyll-include-cache
  # https://primer.style/octicons/packages/jekyll
  - jekyll-octicons
  # https://github.com/benbalter/jekyll-remote-theme
  - jekyll-remote-theme
  # https://github.com/jekyll/jekyll-admin
  - jekyll-admin
# plugins: []
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-remote-theme

# Conversion
# https://jekyllrb.com/docs/configuration/markdown/
# https://docs.github.com/en/github/working-with-github-pages/setting-a-markdown-processor-for-your-github-pages-site-using-jekyll
# markdown: kramdown
markdown: kramdown
# https://jekyllrb.com/docs/liquid/tags/#code-snippet-highlighting
# highlighter: rouge
# lsi: false
# excerpt_separator: \n\n
# incremental: false

# Serving
# detach: false
# port: 4000
# host: 127.0.0.1
# the base hostname & protocol for your site e.g. https://www.someone.com
url: https://genomagames.com
# does not include hostname
baseurl: /genoma-invaders
# show_dir_listing: false

# Outputting
# https://jekyllrb.com/docs/permalinks/#global
# permalink: date
permalink: pretty
# https://jekyllrb.com/docs/pagination/
# paginate_path: /page:num
# see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values
timezone: Europe/Madrid

# quiet: false
# verbose: false
# defaults: []
defaults:
  - scope:
      path: ""
      type: tutorials
    values:
      layout: single
      sidebar:
        nav: tutorial
      toc: true
      toc_label: Index
      toc_icon: file-alt
      toc_sticky: true
      author: AlbertoFdzM
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: false

# liquid:
#   error_mode: warn

# Markdown Processors
# rdiscount:
#   extensions: []

# redcarpet:
#   extensions: []

# https://jekyllrb.com/docs/configuration/markdown/
# https://kramdown.gettalong.org/options.html
kramdown:
  input: GFM # GFM, kramdown
  parse_block_html: true
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

## PLUGINS ##

# https://github.com/jekyll/jekyll-feed
feed:
  path: /index.xml
  collections:
    tutorials:
      path: /feed.xml

# https://github.com/jekyll/jekyll-mentions
jekyll-mentions:
  base_url: https://twitter.com

# https://github.com/benbalter/jekyll-optional-front-matter
optional_front_matter:
  remove_originals: true

# https://github.com/benbalter/jekyll-titles-from-headings
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

# https://github.com/benbalter/jekyll-relative-links
relative_links:
  enabled: true
  collections: true

## THEME ##

# Jekyll Remote Theme, see https://github.com/benbalter/jekyll-remote-theme for more information.

# https://raw.githubusercontent.com/mmistakes/minimal-mistakes/4.19.3/_config.yml
# theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes@4.19.3
minimal_mistakes_skin: genoma # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
locale: en-US
title: Genoma Games
title_separator: "-"
subtitle:
name: Genoma Games
description: >-
  2D Game Shoot 'em Up like Space Invaders made to teach Game Development with Unity.
home_url: /../
repository: GenomaGames/genoma-invaders
repository_tree: gh-pages
head_scripts:
teaser:
logo: /assets/icon_156.png
# https://mmistakes.github.io/minimal-mistakes/docs/navigation/#breadcrumbs-beta
breadcrumbs: true
words_per_minute: 300

# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#comments
comments:
  provider: disqus
  disqus:
    shortname: genoma-games

# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#custom-feed-url
# atom_feed:
#   path: "http://feeds.feedburner.com/youFeedname"

# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-search
# search: true
# search_full_content: false
# search_provider: lunr

# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#seo-social-sharing-and-analytics-settings
google_site_verification:
bing_site_verification:
naver_site_verification:
yandex_site_verification:

# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#twitter-cards-and-facebook-open-graph
twitter:
  username: GenomaGames
facebook:
  username: GenomaGames
  publisher: https://www.facebook.com/GenomaGames
og_image: /assets/icon.png

# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#include-your-social-profile-in-search-results
social:
  type: Organization
  name: Genoma Games
  links:

# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#analytics
analytics:
  provider: google-gtag
  google:
    tracking_id: UA-74490555-3
    anonymize_ip: false

# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-author
# author:
#   name: "Your Name"
#   avatar: "/assets/images/bio-photo.jpg"
#   bio: "I am an **amazing** person." # Note: Markdown is allowed
#   location: "Somewhere"
#   links:
#     - label: "Made Mistakes"
#       icon: "fas fa-fw fa-link"
#       url: "https://mademistakes.com"
#     - label: "Twitter"
#       icon: "fab fa-fw fa-twitter-square"
#       url: "https://twitter.com/mmistakes"
#     - label: "GitHub"
#       icon: "fab fa-fw fa-github"
#       url: "https://github.com/mmistakes"
#     - label: "Instagram"
#       icon: "fab fa-fw fa-instagram"
#       url: "https://instagram.com/mmistakes"

# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-footer
footer:
  links:
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: https://twitter.com/GenomaGames
    - label: Instagram
      icon: fab fa-fw fa-instagram
      url: https://instagram.com/GenomaGames
    - label: Facebook
      icon: fab fa-fw fa-facebook
      url: https://facebook.com/GenomaGames
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/GenomaGames
    - label: feed_label
      icon: fas fa-fw fa-rss-square
      url: /feed.xml

